# Generated by Django 5.2.8 on 2026-03-11 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff Member'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('partner', 'Partner'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('operational', 'Operational'), ('financial', 'Financial'), ('maintenance', 'Maintenance'), ('incident', 'Incident Report')], default='operational', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accountant_approved', 'Accountant Approved'), ('admin_approved', 'Admin Approved (Final)'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('accountant_approved', models.BooleanField(default=False)),
                ('accountant_approved_at', models.DateTimeField(blank=True, null=True)),
                ('accountant_note', models.TextField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('accountant_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_approvals', to=settings.AUTH_USER_MODEL)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
